Update newpkg.md
JuliaReach/JuliaReachDevDocs pull request #14
Opened 2019-08-09 15:46 UTC by mforets

2019-08-09 15:47 UTC, schillic requested changes
Let me first check which of the two fixes does the trick.

2019-08-09 15:48 UTC, mforets commented
ok sure. wanted to PR this so we dont forget. we also have to update JuliaReachTemplatePkg (which is anyways outdated).

2019-08-09 19:16 UTC, schillic commented
This is wrong. What helped was removing `Coveralls` from the command chain.

2019-08-10 09:07 UTC, schillic reviewed
Supposedly this does work. But I think we should first verify.

2019-08-10 09:07 UTC, schillic commented on docs/src/newpkg.md
> +language: julia
It was said that the command should come *after* `language`. I do not think that this makes a difference, but who knows.

2019-08-10 15:54 UTC, schillic approved these changes

2019-08-12 19:37 UTC, merged